/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu.mprincipal;

import igu.alumnos.VerAlumnosPorCurso;
import igu.alumnos.VerDatosAlumno;
import igu.asignacion.AsignarMateriaAlumno;
import igu.asignacion.AsignarMateriasDocente;
import igu.asignacion.AsignarNotaAlumno;
import igu.asignacion.VerAlumnosPorDocente;
import igu.docentes.VerDatosDocentes;
import igu.login.Login;
import igu.notas.BoletinNotas;
import igu.personal.VerDatosPersonal;
import igu.tutores.VerDatosTutor;

/**
 *
 * @author lucia
 */
public class MenuPrincipalPersonal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalPersonal
     */
    public MenuPrincipalPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelRol = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Entidades4 = new javax.swing.JMenu();
        VerAlumnosPorDocente = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        VerAlumnosporCurso = new javax.swing.JMenuItem();
        Entidades1 = new javax.swing.JMenu();
        HorariosyAulas = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        HorariosyAulas1 = new javax.swing.JMenuItem();
        Entidades3 = new javax.swing.JMenu();
        AsignarMaterias2 = new javax.swing.JMenuItem();
        Entidades5 = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAutoscrolls(true);
        jPanel2.setPreferredSize(new java.awt.Dimension(1920, 1080));

        labelRol.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl.setText("Bienvenido");

        lblRol.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(772, 772, 772)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(510, 510, 510)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelRol, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(labelRol, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(173, 173, 173)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(15, 80, 166));
        jMenuBar1.setBorder(null);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(505, 38));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(505, 40));

        Entidades4.setForeground(new java.awt.Color(255, 255, 255));
        Entidades4.setText("Listado de Alumnos");

        VerAlumnosPorDocente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VerAlumnosPorDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/equipo.png"))); // NOI18N
        VerAlumnosPorDocente.setText("Por Docente");
        VerAlumnosPorDocente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerAlumnosPorDocente.setPreferredSize(new java.awt.Dimension(142, 36));
        VerAlumnosPorDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerAlumnosPorDocenteActionPerformed(evt);
            }
        });
        Entidades4.add(VerAlumnosPorDocente);
        Entidades4.add(jSeparator8);

        VerAlumnosporCurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VerAlumnosporCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/equipo.png"))); // NOI18N
        VerAlumnosporCurso.setText("Por Curso");
        VerAlumnosporCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerAlumnosporCurso.setPreferredSize(new java.awt.Dimension(142, 36));
        VerAlumnosporCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerAlumnosporCursoActionPerformed(evt);
            }
        });
        Entidades4.add(VerAlumnosporCurso);

        jMenuBar1.add(Entidades4);

        Entidades1.setForeground(new java.awt.Color(255, 255, 255));
        Entidades1.setText("Materias");

        HorariosyAulas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HorariosyAulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/equipo.png"))); // NOI18N
        HorariosyAulas.setText("Asignar Alumno");
        HorariosyAulas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HorariosyAulas.setPreferredSize(new java.awt.Dimension(142, 36));
        HorariosyAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorariosyAulasActionPerformed(evt);
            }
        });
        Entidades1.add(HorariosyAulas);
        Entidades1.add(jSeparator9);

        HorariosyAulas1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HorariosyAulas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/equipo.png"))); // NOI18N
        HorariosyAulas1.setText("Asignar Docente");
        HorariosyAulas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HorariosyAulas1.setPreferredSize(new java.awt.Dimension(142, 36));
        HorariosyAulas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorariosyAulas1ActionPerformed(evt);
            }
        });
        Entidades1.add(HorariosyAulas1);

        jMenuBar1.add(Entidades1);

        Entidades3.setForeground(new java.awt.Color(255, 255, 255));
        Entidades3.setText("Pagos");

        AsignarMaterias2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AsignarMaterias2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/equipo.png"))); // NOI18N
        AsignarMaterias2.setText("Asignar pago");
        AsignarMaterias2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AsignarMaterias2.setPreferredSize(new java.awt.Dimension(142, 36));
        AsignarMaterias2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarMaterias2ActionPerformed(evt);
            }
        });
        Entidades3.add(AsignarMaterias2);

        jMenuBar1.add(Entidades3);

        Entidades5.setForeground(new java.awt.Color(255, 255, 255));
        Entidades5.setText("Salir");

        Salir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/equipo.png"))); // NOI18N
        Salir.setText("Deslogear");
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.setPreferredSize(new java.awt.Dimension(142, 36));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Entidades5.add(Salir);

        jMenuBar1.add(Entidades5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private VerDatosAlumno ventanaAlumnos;
    private VerDatosDocentes ventanaDocentes;
    private VerDatosPersonal ventanaPersonal;
    // private PagoCuotas ventanaCuotas;
    private AsignarMateriasDocente ventanaAsignarMatDocente;
    private AsignarMateriaAlumno ventanaAsignarMatAlumno;
    private AsignarNotaAlumno ventanaCarga_Notas;
    private BoletinNotas ventanaVer_Notas;
    private Login ventanaLogin;
    private VerDatosTutor ventanaTutor;
    private VerAlumnosPorDocente ventanaAlumnosxDocente;
    private VerAlumnosPorCurso ventanaAlumnosxCurso;
    
    private void HorariosyAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorariosyAulasActionPerformed
        if (ventanaAsignarMatAlumno == null || !ventanaAsignarMatAlumno.isVisible()) {
            ventanaAsignarMatAlumno = new AsignarMateriaAlumno();
        }

        ventanaAsignarMatAlumno.setVisible(true);
        ventanaAsignarMatAlumno.toFront();
    }//GEN-LAST:event_HorariosyAulasActionPerformed

    private void AsignarMaterias2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarMaterias2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AsignarMaterias2ActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        if (ventanaLogin == null || !ventanaLogin.isVisible()) {
            ventanaLogin = new Login();
        }

        ventanaLogin.setVisible(true);
        ventanaLogin.toFront();
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void VerAlumnosPorDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerAlumnosPorDocenteActionPerformed
        if (ventanaAlumnosxDocente == null || !ventanaAlumnosxDocente.isVisible()) {
            ventanaAlumnosxDocente = new VerAlumnosPorDocente();
        }

        ventanaAlumnosxDocente.setVisible(true);
        ventanaAlumnosxDocente.toFront();
    }//GEN-LAST:event_VerAlumnosPorDocenteActionPerformed

    private void VerAlumnosporCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerAlumnosporCursoActionPerformed
        if (ventanaAlumnosxCurso == null || !ventanaAlumnosxCurso.isVisible()) {
            ventanaAlumnosxCurso = new VerAlumnosPorCurso();
        }

        ventanaAlumnosxCurso.setVisible(true);
        ventanaAlumnosxCurso.toFront();
    }//GEN-LAST:event_VerAlumnosporCursoActionPerformed

    private void HorariosyAulas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorariosyAulas1ActionPerformed
        if (ventanaAsignarMatDocente == null || !ventanaAsignarMatDocente.isVisible()) {
            ventanaAsignarMatDocente = new AsignarMateriasDocente();
        }

        ventanaAsignarMatDocente.setVisible(true);
        ventanaAsignarMatDocente.toFront();
    }//GEN-LAST:event_HorariosyAulas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AsignarMaterias2;
    private javax.swing.JMenu Entidades1;
    private javax.swing.JMenu Entidades3;
    private javax.swing.JMenu Entidades4;
    private javax.swing.JMenu Entidades5;
    private javax.swing.JMenuItem HorariosyAulas;
    private javax.swing.JMenuItem HorariosyAulas1;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem VerAlumnosPorDocente;
    private javax.swing.JMenuItem VerAlumnosporCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel labelRol;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblRol;
    // End of variables declaration//GEN-END:variables
}
